FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update

RUN apt-get --yes --force-yes install build-essential

RUN apt-get --yes --force-yes install libgtk-3-dev

RUN apt-get --yes --force-yes install libtbb-dev